AI 폴더 추천 고도화 및 요약 Coverage 개선
mash-up-kr/Dorabangs_Node pull request #106
Opened 2024-09-24 14:45 UTC by J-Hoplin

## PR 내용

## 추가 및 변경 사항

> API endpoint와 추가 혹은 변경된 사항을 적어주세요!

- 마이그레이션(완료상태)
  - Folder Collection, visible 필드
- URL Validator 수정
- Puppeteer Pool 연결
  - Coverage 증가 목적
  - 우선 NCloud에 임시로 배포해둔 상태
  - [배포코드](https://github.com/J-Hoplin/Puppeteer-Pool-API)

- 고도화 기획 사항
~~~
AI 폴더 추천 개선 사항

목표: 클라이언트에서 컴포넌트 변경 없이 프로세스 변경 진행

< DB 변경 사항 >
- Folder에 `visible` 필드 추가: 사용자가 볼 수 있는 필드인지 여부, Migration Script 추가, 기존 데이터들 visible = true로
- Folder 보여줄 때 Visible한 폴더들만 보여주도록 변경

< 프로세스 >
1. 사용자 폴더 + 기존 온보딩 폴더 합쳐서 분류
2. 만약 사용자 폴더가 아닌 경우에는 폴더 추가(visible=false)
3. AI Classification 줄때는 visible true, false 모두 보여준 상태로
4. 만약 사용자가 visible false인 폴더에 대해 모두 이동을 했을때 visible=true로 변경
~~~

## PR 중점사항

> 리뷰어가 중점적으로 봐야하는 부분에 대해 적어주세요!

## 스크린샷

2024-09-24 15:25 UTC, JonghunAn requested changes

2024-09-24 15:25 UTC, JonghunAn commented on migrations/01_folder_visible.migration.ts
> +async function addVisibleField() {
folder에 visible 필드 추가하려고 만든 함수로 보이는데 
이미 DB보니까 반영됐던데 이건 실수로 올린건가?

2024-09-24 15:25 UTC, JonghunAn commented on src/modules/ai-classification/ai-classification.service.ts
> +          } else {
이건 ai 요약 람다 서버에서는 실패했을때랑 동일한 방식으로 처리하는게 좋겠어유~~
요약 실패시 -> post에 aiStatus만 fail로 변경

이건 동일한 기조로 가야된다고 생각함!

2024-09-24 15:25 UTC, JonghunAn commented on src/infrastructure/ai/ai.service.ts
> +      if (tokenCount <= 500) {
500 값이 어려군데에서 쓰이던데 기준값은 constant 값으로 빼두는게 어떨지~~?

2024-09-24 15:25 UTC, JonghunAn commented on src/modules/ai-classification/ai-classification.service.ts
> +      if (payload.postContent.length < 800) {
이건 왜 기준이 800자 이하인거야??

2024-09-24 15:25 UTC, JonghunAn commented on src/modules/classification/classification.repository.ts
> +  async makeFoldersVisible(folderId: string) {
얘는 폴더 repository에 있어야할 것 같은뎅 ㅎㅎ;

2024-09-24 15:30 UTC, JonghunAn commented
저거 폴더 생성했을 때 폴더 개수랑 폴더목록 조회할때 쿼리 조건값에 visible 판단 쿼리 추가되야하지않아?
임의의 aiGenerated 하나 만들어 준다고 했는데 그거 포함될 것 같은데...

2024-09-24 16:00 UTC, J-Hoplin commented on src/modules/ai-classification/ai-classification.service.ts
> +      if (payload.postContent.length < 800) {
아 형 이거 execute부터 Worker Lambda에서 실행되는 부분이야

2024-09-24 16:01 UTC, J-Hoplin commented on src/modules/ai-classification/ai-classification.service.ts
> +      if (payload.postContent.length < 800) {
800은 따로 기준 잡기가 애매한데 일반적으로 파싱이 완료되면 1000자 이상으로 보여서 우선 800으로 했어

2024-09-24 16:06 UTC, J-Hoplin commented on src/modules/ai-classification/ai-classification.service.ts
> +          } else {
이 try ~ catch문 같은 경우에는 fetch API로 파싱이 안된 경우 다시 파싱을 하는게 목적이고 그 다음에 호출되는 `summarizeLinkContent`에서 fail 처리하는 로직이 있어서 이렇게 했는데 내가 이해한게 맞으려낭..

<img width="602" alt="image" src="https://github.com/user-attachments/assets/c138e3a8-a6bd-429a-aecb-83a3afe3b9b8">

2024-09-24 16:11 UTC, J-Hoplin commented
@JonghunAn 음 우선 폴더 API에서 폴더 List 하는 API 하나밖에 영향범위가 없어서 해당 부분은 적용을 해둔 상태고, AiClassification 부분에서는 visible 여부 상관 없이 모두 보여줘야하는 상황이라 classification list API에서 visible 필터 안걸어서 가져오도록 해두었어
<img width="561" alt="image" src="https://github.com/user-attachments/assets/201d65a3-bc85-45e0-a7b1-7c601a044e5e">

2024-09-24 16:12 UTC, J-Hoplin commented on src/infrastructure/ai/ai.service.ts
> +      if (tokenCount <= 500) {
그러게 이거는 constant에 빼두고 관리하는게 나을꺼같당

2024-09-24 16:18 UTC, J-Hoplin commented on migrations/01_folder_visible.migration.ts
> +async function addVisibleField() {
마이그레이션 파일은 지우는거로!

2024-09-25 04:06 UTC, JonghunAn commented on src/modules/ai-classification/ai-classification.service.ts
> +          } else {
아 확인확인 else에서 throw 해도 catch에서 받아서 요약실패로 처리되겠구나

2024-09-25 04:06 UTC, JonghunAn commented on src/modules/ai-classification/ai-classification.service.ts
> +        );
https://github.com/mash-up-kr/Dorabangs_Node/pull/106#issuecomment-2371736114
요거에 대한 답변인데

폴더 여기서 생성하면 내부적으로 내폴더 목록조회때 안보여야하는데
https://api-dev.link-it.co.kr/docs#/Folder%20API/FoldersController_findAll

여기서 노출될 것 같아서!

2024-09-25 04:07 UTC, JonghunAn commented on src/modules/ai-classification/ai-classification.service.ts
> +      if (payload.postContent.length < 800) {
아 확인확인 else에서 throw 해도 catch에서 받아서 요약실패로 처리되겠구나

2024-09-25 04:15 UTC, JonghunAn commented on src/modules/ai-classification/ai-classification.service.ts
> +      if (payload.postContent.length < 800) {
아 그러면 우리 기존에 쓰던 parser.util에 parseLinkTitleAndContent 함수를 쓰잖아 
근데 기존에 요약안되던 링크들도 workerLambda 이벤트로 던지는 payload에 content length가 1000자로 정상적으로 오는거지?

원래 요약이 정상적으로 안되는 경우들중에 parseLinkTitleAndContent에서 가져온 content가 정상적으로 html 파싱이 안되던 경우들이라
지금처럼 처리하면 html 파싱이 재대로 안된경우들은 퍼페티어로 처리가 안될 것 같은데 아닌가?

2024-09-25 07:23 UTC, hye-on commented on src/modules/ai-classification/ai-classification.service.ts
> +      if (summarizeUrlContent.success && !summarizeUrlContent.isUserCategory) {
넘넘 사소하지만 조건문 설명 필요하면 함수로 따로 빼는것도 좋을 듯!!
(그냥 두는 게 더 좋은 것 같기도..?)
ex) `shouldCreateFolderIfNotUserCategory`

2024-09-25 14:16 UTC, J-Hoplin commented on src/modules/ai-classification/ai-classification.service.ts
> +      if (payload.postContent.length < 800) {
아 여기서 html파싱이 안됐다는거는 결국 모든 요청은 Content가 있기때문에 불러오는데, 나무위키같이 페이지내 CSR JavaScript 실행이 필요한데 안된경우를 이야기 하는거야! 우선 모든 URL은 클라이언트에서 기본적으로 Validation을 거쳐서 요청이 이루어지기 때문에 우선은 모든 URL자체는 Content가 담긴 URL이라는 가정으로 생각했어

2024-09-25 14:25 UTC, J-Hoplin commented on src/modules/ai-classification/ai-classification.service.ts
> +        );
이 부분같은 경우에 FolderService의 `findAll` 를 호출하는데, `findAll`은 FolderRepository의 `findByUserId`를 통해서 전체 폴더를 우선 들고오는데 이번 PR에서 이 메소드에 `true`를 기본값으로 갖는 `onlyVisible` 매개변수를 추가했어! 그렇기 때문에 따로 변경 없이도 visible=true에 해당하는 폴더 목록만 가져오게 변경했으~ 레포지토리에 매개변수를 추가한 이유는 Folder, Post, Classification에서 모두 의존하고 있기때문에 변동성을 최소화 하기 위해 추가했고 전체를 가져와서 Lambda를 호출하는 PostCreate에서는 false로 줘서 전체를 가져올 수 있도록 적용한거야~

<img width="458" alt="image" src="https://github.com/user-attachments/assets/47b991ea-5e16-4500-a7aa-41017496f517">
<img width="1208" alt="image" src="https://github.com/user-attachments/assets/b9f39cf8-69ed-425f-a0c3-55bf2edf238c">
<img width="521" alt="image" src="https://github.com/user-attachments/assets/f4b0ec32-3580-4116-bd05-67e885a6e526">

2024-09-25 14:39 UTC, J-Hoplin commented on src/modules/ai-classification/ai-classification.service.ts
> +        );
Swagger로 테스트한거를 보여주면 새로운 Post를 생성한 후에 Classification은 만들어졌지만 Folder 목록에서는 볼 수 없고 분류 후에 나오는 과정이야!
<img width="628" alt="image" src="https://github.com/user-attachments/assets/83c8d59a-f869-44f4-8deb-e1766f7ad213">
<img width="633" alt="image" src="https://github.com/user-attachments/assets/8dbb321e-e7a7-43a8-9f5f-c1ebf195a3bc">
<img width="671" alt="image" src="https://github.com/user-attachments/assets/dc4b55ca-1d42-4830-871f-a6d0bafb940f">
<img width="602" alt="image" src="https://github.com/user-attachments/assets/3cfdbef9-82cf-4cba-a9bb-77e2a569b1e6">

2024-09-25 16:59 UTC, Marades commented on src/modules/ai-classification/ai-classification.service.ts
> +      if (summarizeUrlContent.success && !summarizeUrlContent.isUserCategory) {
나도 아직은 변수나 함수로 빼야할 필요성까진 없을 거 같아~
변수로 빼는 거 정도는 개인 스타일일 듯?!

2024-09-25 17:04 UTC, Marades commented on src/modules/ai-classification/ai-classification.service.ts
> +          const puppeteerURL = this.config.get<string>('PUPPETEER_POOL_URL');
puppeteer 쪽 로직이 별도의 함수나 service로 있으면 어떨까?!
ai classification execute함수에 컨텍스트가 많아서 함수 분리 정도는 해두면 어떨까 하는 생각이 드넹

content정도만 return 해서 본 함수에서 사용하는 식으로?

2024-09-25 17:05 UTC, Marades commented on src/modules/folders/folders.repository.ts
> +  async makeFoldersVisible(folderId: string) {
makeFoldersVisible인데 folderId는 단수당

2024-09-25 17:08 UTC, Marades commented on src/ai_handler.ts
> +    FoldersModule,
요건 다시 지우면 안되는 모듈이얌?

2024-09-27 10:22 UTC, JonghunAn commented on src/modules/ai-classification/ai-classification.service.ts
> +          } else {
네네  맞습니다 ~ 내가 조건문 scope를 잘못봤어 ㅋㅋ

2024-09-27 10:27 UTC, JonghunAn commented on src/modules/ai-classification/ai-classification.service.ts
> +      if (summarizeUrlContent.success && !summarizeUrlContent.isUserCategory) {
나도 건회랑 의견은 비슷해~
내가 함수로 빼두는 기준은 받아온 값에 대해서 뭔가 비지니스 로직이 필요할때라... +ㅡ+

단순 상태 조건 체크는 나는 괜찮아보여~

2024-09-27 10:47 UTC, J-Hoplin commented on src/ai_handler.ts
> +    FoldersModule,
삭제해도 괜찮아!

2024-09-27 11:39 UTC, J-Hoplin commented on src/modules/ai-classification/ai-classification.service.ts
> +          const puppeteerURL = this.config.get<string>('PUPPETEER_POOL_URL');
적용완료!

2024-09-27 11:51 UTC, hye-on commented on src/modules/ai-classification/ai-classification.service.ts
> +      if (summarizeUrlContent.success && !summarizeUrlContent.isUserCategory) {
옹 이제봤네 나도 좋아ㅏ

2024-09-29 03:31 UTC, Marades approved these changes

2024-09-29 03:50 UTC, JonghunAn approved these changes

2024-09-29 03:52 UTC, merged