Feat : AI 분류 폴더 이름 리스트get  api, AI 분류 링크 리스트 get  api
mash-up-kr/Dorabangs_Node pull request #26
Opened 2024-06-29 17:15 UTC by hye-on

## PR 내용
- BaseDocument 의 createdAt, updatedAt을 타입을 string에서 Date로 수정
- AI 분류 폴더 이름 리스트 get api
- AI 분류 링크 리스트 get api
- postAIClassification의 keywords타입을 string으로 변경

## PR 중점사항
잘 부탁드립니다

2024-06-29 18:16 UTC, Marades commented on src/modules/classification/classification.service.ts
> +    @InjectModel(Post.name) private postModel: Model<Post>,
이부분 나중에 repo로 빼보면 좋을 거 같당

2024-06-29 18:20 UTC, hye-on commented on src/modules/classification/classification.service.ts
> +    @InjectModel(Post.name) private postModel: Model<Post>,
오키!!

2024-06-29 18:24 UTC, Marades commented on src/modules/classification/classification.service.ts
> +    const folders = await this.folderModel.find({ userId }).exec();
요거 내가 folderRepo에 findByUserId라는 메소드로 만들어놨으~

2024-06-29 18:26 UTC, Marades commented on src/modules/classification/dto/getAIFolderNameLIst.dto.ts
> +    (this.id = data._id.toString()), (this.name = data.name);
요 부분 먼가 포매팅이 잘못 된 거 같당

2024-06-29 19:09 UTC, JonghunAn requested changes

2024-06-29 19:09 UTC, JonghunAn commented on src/modules/classification/dto/getAIPostList.dto.ts
> +  }
```suggestion
  constructor(post: postSchema, ai: aiClassificationSchema ) {
    this.id = post.id;
    this.title = post.title;
    this.url = post.url;
    this.description = post.description;
    this.keywords = ai.keywords;
    this.createdAt = ai.aiClassificationId.createdAt;
  }
```

2024-06-29 19:09 UTC, JonghunAn commented on src/modules/classification/classification.service.ts
> +    return matchedFolders.map((folder) => new AIFolderNameServiceDto(folder));
**(˵ •̀ ᴗ - ˵ ) ✧**
여기서 serviceDto 만들어줄때 schema 별로 분리해서 생성해봐~
```suggestion
    return matchedFolders.map((folder) => new AIFolderNameServiceDto(folder, folder. aiClassificationId));
```

2024-06-29 19:09 UTC, JonghunAn commented on src/modules/classification/dto/getAIPostList.dto.ts
> +  };
(˵ •̀ ᴗ - ˵ ) ✧
요건 serviceDto에서 constructor에서 paramter 받을때 도메인 스키마별로 받으면 필요없음!

2024-06-29 19:09 UTC, JonghunAn commented on src/modules/classification/dto/getAIPostList.dto.ts
> +}
**(˵ •̀ ᴗ - ˵ ) ✧**
ResponseDto는 `/classification/response` 아래에 별도 클래스 파일로 분리해줘~

2024-06-29 19:12 UTC, J-Hoplin commented on src/modules/classification/classification.service.ts
> +  async getPostList(folderId: string): Promise<AIPostServiceDto[]> {
혜온아 이부분도 `@GetUser`로 사용자 ID 가져와서 사용자 분기도 같이 해줘야할것 같아!

2024-06-29 19:12 UTC, Marades commented on src/modules/classification/dto/getAIFolderNameLIst.dto.ts
> +  @IsString()
service dto라서 요 데코레이터들도 빼도 될 거 같아!

2024-06-29 19:22 UTC, JonghunAn commented on src/modules/classification/classification.controller.ts
> +@Controller('ai')
```suggestion
@Controller('classification')
```

2024-06-29 19:22 UTC, JonghunAn commented on src/infrastructure/database/schema/postAIClassification.schema.ts
> +export class PostAIClassification extends BaseDocument {
```suggestion
export class AIClassification extends BaseDocument {
```

2024-07-02 08:57 UTC, hye-on commented on src/modules/classification/classification.service.ts
> +    const folders = await this.folderModel.find({ userId }).exec();
오빠꺼 아직 머지 안되서 머지되면 수정할께!

2024-07-02 08:57 UTC, hye-on commented on src/modules/classification/dto/getAIFolderNameLIst.dto.ts
> +    (this.id = data._id.toString()), (this.name = data.name);
오키!

2024-07-02 08:58 UTC, hye-on commented on src/infrastructure/database/schema/post.schema.ts
> +  //TODO : 사진 추가
오키!

2024-07-02 09:01 UTC, hye-on commented on src/modules/classification/classification.service.ts
> +    const folderIds = folders.map((folder) => folder._id);
오호 땡큐
건회오빠가 만들어둔  findByUserId 써서 수정할께!

2024-07-02 10:09 UTC, hye-on commented on src/modules/classification/classification.service.ts
> +    ];
오키!

2024-07-02 10:09 UTC, hye-on commented on src/modules/classification/dto/getAIPostList.dto.ts
> +  }
오키

2024-07-02 10:23 UTC, hye-on commented on src/modules/classification/dto/getAIFolderNameLIst.dto.ts
> +  @IsString()
서비스 dto에서 스웨거 관련 데코레이터도 제거해?
스웨거에서 스키마 볼 때 필요하지 않나해서

2024-07-02 10:43 UTC, hye-on commented on src/infrastructure/database/schema/postAIClassification.schema.ts
> +export class PostAIClassification extends BaseDocument {
[0df80c4](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/0df80c4bcbe2085d4a38754f5b5c4947e22e8383)

2024-07-02 10:43 UTC, hye-on commented on src/modules/classification/classification.controller.ts
> +@Controller('ai')
[33f950a](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/33f950a4ed300f6080ec6c09de45fd01f1a1430d)

2024-07-02 10:44 UTC, hye-on commented on src/modules/classification/dto/getAIFolderNameLIst.dto.ts
> +  @IsString()
[bd3c19b](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/bd3c19bef812c8d76b9f9ee8eb8e28ba047fa1b8)

[e4e0f1c](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/e4e0f1c7f8166f0d0900a1281703bec524cb0506)

2024-07-02 10:44 UTC, hye-on commented on src/modules/classification/classification.service.ts
> +  async getPostList(folderId: string): Promise<AIPostServiceDto[]> {
[9764ef8](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/9764ef8e8946f1713882944948a1704b2ddc5289)

2024-07-02 10:45 UTC, hye-on commented on src/modules/classification/dto/getAIPostList.dto.ts
> +}
[68e4b20](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/68e4b20859080aaa29922558f41e089f0efee4e0)

2024-07-02 10:45 UTC, hye-on commented on src/modules/classification/dto/getAIPostList.dto.ts
> +  };
[09892b7](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/09892b79f7bab223c68702a4d55752ee2eef6604)

2024-07-02 10:46 UTC, hye-on commented on src/modules/classification/classification.service.ts
> +    return matchedFolders.map((folder) => new AIFolderNameServiceDto(folder));
[09892b7](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/09892b79f7bab223c68702a4d55752ee2eef6604)

2024-07-02 10:46 UTC, hye-on commented on src/modules/classification/dto/getAIPostList.dto.ts
> +  }
[09892b7](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/09892b79f7bab223c68702a4d55752ee2eef6604)

2024-07-02 10:47 UTC, hye-on commented on src/modules/classification/classification.service.ts
> +    ];
[53e166c](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/53e166c60ea7269ae91bbef4314b8d6dd7655516)

2024-07-02 10:47 UTC, hye-on commented on src/infrastructure/database/schema/post.schema.ts
> +  //TODO : 사진 추가
[aea6e40](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/aea6e405e0cfabbda0997e5f5e399f031dda2986)

2024-07-02 10:48 UTC, hye-on commented on src/modules/classification/dto/getAIFolderNameLIst.dto.ts
> +    (this.id = data._id.toString()), (this.name = data.name);
[68ade94](https://github.com/mash-up-kr/Dorabangs_Node/pull/26/commits/68ade94548814f0f16a3d3462efe2c2662946d34)

2024-07-02 13:05 UTC, J-Hoplin approved these changes
수고했어!!👍

2024-07-02 13:14 UTC, JonghunAn approved these changes

2024-07-02 13:16 UTC, merged